### ISSUE TITLE
Instabot failing to comment

### ISSUE THREAD

**Issue by l8ton** [nickpettican/InstaBot#17] opened 2017-10-18 10:44 UTC
[ 2017-10-18 11:32:08 ]  * Trying to comment https://www.instagram.com/p/BaYqwOqnhIB/... Error: while commenting - debugging needed: in explore operation - debugging needed: sequence item 0: expected string, list found

My log is filled with the above error.

**Comment by nickpettican** [comment] 2017-10-18 11:21
Hi @l8ton , thanks for the feedback, I believe the problem is with the `generate_comment` function.
Could you show me the `comments_list` you used in your config.json to generate the comments?

**Comment by l8ton** [comment] 2017-10-18 13:08
"comments_in_day": 80,
	"comments_list": [["Cool", "Sweet", "Awesome", "Great"],
						["ðŸ˜„", "ðŸ™Œ", "ðŸ‘", "ðŸ‘Œ", "ðŸ˜Š"], 
						[".", "!", "!!", "!!!"]],

Here you go :)

**Comment by nickpettican** [comment] 2017-10-18 14:50
Nice one, I found the issue: I forgot to add `*` when converting the comment list to an itertools product.
If you download the latest version it should be fixed, but let me know if it's still present.

**Comment by nickpettican** [comment] 2017-10-19 11:29
I'm closing the issue, if you see the error is still appearing feel free to reopen!

**Comment by nickpettican** [comment] 2017-10-19 11:30
I'm closing the issue, if you see the error is still appearing feel free to reopen!

**Closed by nickpettican** 2017-10-19 11:30 UTC
Labels: bug
