### ISSUE TITLE
error import arrow module

### ISSUE THREAD

**Issue by polzav** [nickpettican/InstaBot#38] opened 2018-08-01 19:26 UTC
how to fix it?
`Traceback (most recent call last):
  File "run.py", line 23, in <module>
    from src.instabot import InstaBot
  File "/home/instabot/src/instabot.py", line 23, in <module>
    import arrow
ImportError: No module named arrow`

**Comment by nickpettican** [comment] 2018-08-09 20:36
Duplicate of #24

**Closed by nickpettican** 2018-08-09 20:36 UTC
